### ISSUE TITLE
Problème de récupération de côte

### ISSUE THREAD

**Issue by aymericl** [pretrehr/Sports-betting#5]
Bonjour, 

Merci pour votre travail, cependant j'ai remarqué quelques problèmes lors de la récupération des côtes chez certains bookmaker. j'ai actuellement 4 ou 5 bookmakers uniquement qui fonctionnent "winamax","pmu","france_pari","zebet","netbet".

Une correction est-il prévu ?

**Comment by pretrehr** [comment]
Bonjour,
Merci pour votre message.
Je n'ai pas ce problème de mon côté. Avez-vous un message d'erreur qui s'affiche dans la console lorsque vous récupérez les cotes des autres bookmakers ?

**Comment by aymericl** [comment]
C'est un problème selenium, mais ce que je comprends pas c'est que ça marche pour certains et pas pour d'autre.


`FileNotFoundError: [WinError 2] Le fichier sp▒cifi▒ est introuvable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aym▒\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Aym▒\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "interface_pysimplegui.py", line 565, in parse_thread
    parse_competitions(selected_competitions, sport, *selected_sites)
  File "D:\Developpement\Sports-betting\sportsbetting\user_functions.py", line 143, in parse_competitions
    if selenium_init.start_selenium(site, headless, timeout=20):
  File "C:\Users\Aym▒\AppData\Local\Programs\Python\Python38-32\lib\site-packages\stopit\utils.py", line 145, in wrapper
    result = func(*args, **kwargs)
  File "D:\Developpement\Sports-betting\sportsbetting\selenium_init.py", line 41, in start_selenium
    DRIVER[site] = selenium.webdriver.Chrome(get_path(), options=options)
  File "C:\Users\Aym▒\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Aym▒\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
`

**Comment by pretrehr** [comment]
Je pense voir où est le problème. Je poste un fix dans la soirée, je vous tiens au courant

**Comment by pretrehr** [comment]
Normalement ça devrait marcher maintenant. N'hésitez pas à revenir vers moi en cas de problème.

**Comment by aymericl** [comment]
Je confirme, ça fonctionne parfaitement.

Je te remercie.

Good job !
